---
name: devcontainer-features-test

on:
  workflow_call:
    inputs:
      filter_file_path:
        description: Path to YAML file populated with filters.
        required: false
        default: .github/filters.yml
        type: string

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      features: ${{ steps.filter.outputs.changes }}
    permissions:
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: ${{ inputs.filter_file_path }}

  test:
    needs:
      - changes
    if: needs.changes.outputs.features != '' && toJson(fromJson(needs.changes.outputs.features)) != '[]'
    runs-on: ${{ matrix.architectures }}
    continue-on-error: true
    strategy:
      matrix:
        architectures:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        features: ${{ fromJSON(needs.changes.outputs.features) }}
        baseImages:
          - ubuntu:24.04
          - debian:12
          - mcr.microsoft.com/devcontainers/base:ubuntu24.04
          - mcr.microsoft.com/devcontainers/base:debian12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Generate tests for ${{ matrix.features }} against ${{ matrix.baseImages }}
        run: devcontainer features test  --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImages }} .

  scenarios:
    needs:
      - changes
    if: needs.changes.outputs.features != '' && toJson(fromJson(needs.changes.outputs.features)) != '[]'
    runs-on: ${{ matrix.architectures }}
    continue-on-error: true
    strategy:
      matrix:
        architectures:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        features: ${{ fromJSON(needs.changes.outputs.features) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Testing ${{ matrix.features }} scenarios
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated  .
